FROM node:23-alpine

ARG HTTP_PROXY
ARG HTTPS_PROXY
ARG ALL_PROXY
ARG NO_PROXY

RUN apk add --no-cache python3 make g++ gcc chromium ffmpeg

ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 \
    PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /usr/src/app

ARG NODE_ENV=production
ENV NODE_ENV=development

COPY package*.json ./
RUN npm install --include=dev

COPY . .
RUN ./node_modules/.bin/tsc -p tsconfig.server.json

ENV NODE_ENV=${NODE_ENV}

EXPOSE 3011
CMD ["node", "./dist/index.js"]
